# Generated by Django 4.2 on 2025-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartItems', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='order',
            name='cartitems',
            field=models.ManyToManyField(to='CartItems.cartitems'),
        ),
    ]
